module.exports = {
    questions: [
        {
            id: 1,
            question: `Javascript is an _______ language?`,
            is_program_question: false,
            program_question: String,
            choices: {
                a: `Object-Oriented`,
                b: `Object-Based`,
                c: `Procedural`,
                d: `None of the Above`,
            },
            answer: `a`,
            difficulty: "easy",
        },
        {
            id: 2,
            question: `Which of the following keywords is used to define a variable in Javascript?`,
            is_program_question: false,
            program_question: String,
            choices: {
                a: `var`,
                b: `let`,
                c: `Both a and b`,
                d: `None of the Above`,
            },
            answer: `c`,
            difficulty: "easy",
        },
        {
            id: 3,
            question: `Which of the following methods is used to access HTML elements using Javascript?`,
            is_program_question: false,
            program_question: String,
            choices: {
                a: `getElementbtId()`,
                b: `getElementsByClassName()`,
                c: `Both a and b`,
                d: `None of the Above`,
            },
            answer: `c`,
            difficulty: "easy",
        },
        {
            id: 4,
            question: `Upon encountering empty statements, what does the Javascript Interpreter do?`,
            is_program_question: false,
            program_question: String,
            choices: {
                a: `Throws an Error`,
                b: `Ignores the Statements`,
                c: `Gives a Warning`,
                d: `None of the Above`,
            },
            answer: `b`,
            difficulty: "easy",
        },
        {
            id: 5,
            question: `Which of the following methods can be used to display data in some form using Javascript?`,
            is_program_question: false,
            program_question: String,
            choices: {
                a: `document.write()`,
                b: `console.log()`,
                c: `window.alert()`,
                d: `All of the Above`,
            },
            answer: `d`,
            difficulty: "easy",
        },
    ],
};
